#!/bin/bash

# Copies an OpenVPN .ovpn configuration file as provided by PureVPN to
# the docker volume that is mounted by the gluetun container.

set -e

DATA_VOLUME="purevpn-public-ip-vpn-data"

if [ "$1" = "" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     echo "install-ovpn-file: Copies an OpenVPN .ovpn configuration file as provided by PureVPN to a docker volume that isused by this stack." >&2
    echo "Usage: $0 <purevpn-ovpn-file>" >&2
    echo >&2
    echo "To install from stdin, use - as the filename." >&2
    exit 1
fi

if ! docker volume create --name="$DATA_VOLUME" >/dev/null; then
    echo "Unable to create docker volume $DATA_VOLUME" >&2
    exit 1
fi

SRC_FILE="$1"
if [ "$1" = "-" ]; then
    SRC_FILE="/dev/stdin"
fi
if ! docker run --rm -i -v "$DATA_VOLUME:/data" alpine:3.18 sh -c 'cat > /data/purevpn.ovpn.tmp && chmod 600 /data/purevpn.ovpn.tmp && mv /data/purevpn.ovpn.tmp /data/purevpn.ovpn' < "$SRC_FILE"; then
    echo "Unable to copy $SRC_FILE to docker volume $DATA_VOLUME" >&2
    exit 1
fi
